name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - 'Main/**'
      - 'eks/**'
      - 'argocd_deployment/**'
      - 'kubernets-ingress/**'
      - 'iam/**'
      - '.github/**'

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_LOG: DEBUG
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Restore State File
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          STATE_BUCKET="ecommerce-demo-terraform-state-${ACCOUNT_ID}"
          STATE_KEY="infrastructure/ecommerce-k8s-demo.tfstate"

          aws s3api copy-object \
            --bucket "$STATE_BUCKET" \
            --copy-source "$STATE_BUCKET/$STATE_KEY?versionId=C9zNKhyKdhuxweScKIpFnNHAOx6z__Ad" \
            --key "$STATE_KEY"

          echo "✅ State file restored"

      - name: Terraform Init
        working-directory: Main
        run: |
          terraform init \
            -reconfigure \
            -backend-config="bucket=ecommerce-demo-terraform-state-$(aws sts get-caller-identity --query Account --output text)" \
            -backend-config="key=infrastructure/ecommerce-k8s-demo.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="encrypt=true"

      - name: Terraform Plan
        working-directory: Main
        env:
          TF_LOG: DEBUG
        run: |
          terraform plan \
            -lock-timeout=5m \
            -var-file="environments/eks-demo-dev.tfvars" \
            -out=tfplan

      - name: Upload Plan
        env:
          TF_LOG: DEBUG
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: Main/tfplan


  apply:
    runs-on: ubuntu-latest
    needs: plan                  # ← waits for plan to finish
    environment: production      # ← triggers manual approval gate

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: Main
        run: |
          terraform init \
            -backend-config="bucket=ecommerce-demo-terraform-state-$(aws sts get-caller-identity --query Account --output text)" \
            -backend-config="key=infrastructure/ecommerce-k8s-demo.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="encrypt=true"

      - name: Download Plan
        env:
          TF_LOG: DEBUG
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: Main/

      - name: Terraform Apply
        env:
          TF_LOG: DEBUG
        working-directory: Main
        run: terraform apply -auto-approve tfplan