name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - 'Main/**'
      - 'eks/**'
      - 'argocd_deployment/**'
      - 'kubernets-ingress/**'
      - 'iam/**'
      - '.github/**'

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_LOG: DEBUG
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: Main
        run: |
          terraform init \
            -backend-config="bucket=ecommerce-demo-terraform-state-$(aws sts get-caller-identity --query Account --output text)" \
            -backend-config="key=infrastructure/ecommerce-k8s-demo.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="encrypt=true"

      - name: Import Route53 Zone
        working-directory: Main
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          
          # Debug — list all zones to see exact format
          echo "All hosted zones:"
          
          ZONE_ID=$(aws route53 list-hosted-zones --output json | python3 -c "import sys,json;data=json.load(sys.stdin);domain='$DOMAIN_NAME';[print(z['Id'].split('/')[-1]) for z in data['HostedZones'] if z['Name'].rstrip('.')==domain.rstrip('.')]")
          
          echo "Zone ID found: $ZONE_ID"

          if [ -n "$ZONE_ID" ] && [ "$ZONE_ID" != "None" ]; then
            echo "Importing zone $ZONE_ID"
            terraform import \
              -lock=false \
              -var-file="environments/eks-demo-dev.tfvars" \
              -var="domain_name=$DOMAIN_NAME" \
              module.kubernetes_ingress.aws_route53_zone.main \
              $ZONE_ID || echo "Already imported"
          else
            echo "No existing zone found - will be created"
          fi

      - name: Terraform Plan
        working-directory: Main
        env:
          TF_LOG: DEBUG
        run: |
          terraform plan \
            -lock-timeout=5m \
            -var-file="environments/eks-demo-dev.tfvars" \
            -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
            -out=tfplan

      - name: Upload Plan
        env:
          TF_LOG: DEBUG
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: Main/tfplan


  apply:
    runs-on: ubuntu-latest
    needs: plan                  # ← waits for plan to finish
    environment: production      # ← triggers manual approval gate

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: Main
        run: |
          terraform init \
            -backend-config="bucket=ecommerce-demo-terraform-state-$(aws sts get-caller-identity --query Account --output text)" \
            -backend-config="key=infrastructure/ecommerce-k8s-demo.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="encrypt=true"

      - name: Download Plan
        env:
          TF_LOG: DEBUG
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: Main/

      - name: Terraform Apply
        env:
          TF_LOG: DEBUG
        working-directory: Main
        run: terraform apply -auto-approve tfplan